version: '3'

services:
    api:
        build: ./backend
        ports:
            - '8080:8080'
        depends_on:
            - database
    # frontend:

    database:
        image: postgres
        restart: always
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
